INSERT INTO atividades (codigo_item, descricao, unidade, umd_unitaria, categoria_id, ativo)
VALUES ('653511', 'Retirar Estrutura P1, P2, TP1, TP2 HE', 'conjunto', 0.1568, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653513', 'Instalar Estrutura P3 HE', 'conjunto', 0.686, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653514', 'Retirar Estrutura P3 HE', 'conjunto', 0.2744, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653516', 'Instalar Estrutura P4 HE', 'conjunto', 0.98, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653517', 'Retirar Estrutura P4 HE', 'conjunto', 0.392, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653519', 'Instalar estrutura CE1 e CE1A HE', 'conjunto', 0.42, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653520', 'Retirar estrutura CE1 e CE1A HE', 'conjunto', 0.28, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653521', 'Instalar estrutura CE2 HE', 'conjunto', 0.415, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653522', 'Retirar estrutura CE2 HE', 'conjunto', 0.277, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653523', 'Instalar estrutura CE3 HE', 'conjunto', 0.831, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653524', 'Retirar estrutura CE3 HE', 'conjunto', 0.415, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653525', 'Instalar estrutura CE4 HE', 'conjunto', 1.385, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653526', 'Retirar estrutura CE4 HE', 'conjunto', 0.692, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653537', 'Instalação de cobertura protetora permanente para cabo nú HE', 'Unidade', 0.305, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653538', 'Instalação do braço antibalanço HE', 'Unidade', 0.056, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653539', 'Remoção do braço antibalanço HE', 'Unidade', 0.028, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653541', 'Instalar Estrutura Tipo HS HE', 'conjunto', 1.12, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653542', 'Retirar  Estrutura Tipo HS HE', 'conjunto', 0.448, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653544', 'Instalar Estrutura Tipo HT HE', 'conjunto', 2.8, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653545', 'Retirar  Estrutura Tipo HT HE', 'conjunto', 1.12, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653579', 'Instalação do suporte L ou espaçador losangular HE', 'Unidade', 0.14, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('653580', 'Remoção do suporte L ou espaçador losangular HE', 'Unidade', 0.07, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA TRIFÁSICA') LIMIT 1), true),
('632181', 'Instalar Estrutura Tipo U1, UP1', 'conjunto', 0.06, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632182', 'Retirar  Estrutura Tipo U1, UP1', 'conjunto', 0.024, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632184', 'Instalar Estrutura Tipo U1,UP1 HE', 'conjunto', 0.083, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632185', 'Retirar  Estrutura Tipo U1,UP1 HE', 'conjunto', 0.033, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632191', 'Instalar Estrutura Tipo U2, UP2', 'conjunto', 0.08, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632192', 'Retirar  Estrutura Tipo U2, UP2', 'conjunto', 0.032, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632194', 'Instalar Estrutura Tipo U2,UP2 HE', 'conjunto', 0.111, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632195', 'Retirar  Estrutura Tipo U2,UP2 HE', 'conjunto', 0.044, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632201', 'Instalar Estrutura Tipo U3, UP3', 'conjunto', 0.1, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632202', 'Retirar  Estrutura Tipo U3, UP3', 'conjunto', 0.04, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632204', 'Instalar Estrutura Tipo U3,UP3 HE', 'conjunto', 0.139, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632205', 'Retirar  Estrutura Tipo U3,UP3 HE', 'conjunto', 0.055, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632211', 'Instalar Estrutura Tipo U4, UP4', 'conjunto', 0.2, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632212', 'Retirar  Estrutura Tipo U4,UP4', 'conjunto', 0.08, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632214', 'Instalar Estrutura Tipo U4,UP4 HE', 'conjunto', 0.277, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632215', 'Retirar  Estrutura Tipo U4,UP4 HE', 'conjunto', 0.111, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA MONOFÁSICA') LIMIT 1), true),
('632231', 'Instalar Estrutura Tipo HS', 'conjunto', 0.8, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632232', 'Retirar  Estrutura Tipo HS', 'conjunto', 0.32, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632241', 'Instalar Estrutura Tipo HT', 'conjunto', 2, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632242', 'Retirar  Estrutura Tipo HT', 'conjunto', 0.8, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632321', 'Nivelar e Alinhar Cruzeta', 'Unidade', 0.04, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632324', 'Nivelar e Alinhar Cruzeta HE', 'Unidade', 0.055, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632331', 'Revisar Cruzeta no Alto da Estrutura', 'conjunto', 0.01, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632334', 'Revisar Cruzeta no Alto da Estrutura HE', 'conjunto', 0.014, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632341', 'Inst. Pino Cruzeta ou Topo com Isolador', 'Unidade', 0.06, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632342', 'Ret. Pino de Cruzeta ou Topo com Isol.', 'Unidade', 0.024, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632344', 'Inst. Pino Cruzeta ou Topo c Isolador HE', 'Unidade', 0.083, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632345', 'Ret. Pino de Cruzeta ou Topo c Isol. HE', 'Unidade', 0.033, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632381', 'Instalar Isolador de Disco / Bastão', 'cada', 0.1, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632382', 'Retirar  Isolador de Disco / Bastão', 'cada', 0.04, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632384', 'Instalar Isolador de Disco / Bastão HE', 'cada', 0.139, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632385', 'Retirar  Isolador de Disco / Bastão HE', 'cada', 0.055, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632431', 'Lavação de Isoladores', 'conjunto', 0.18, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('632434', 'Lavação de Isoladores HE', 'conjunto', 0.25, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE ALTA ANTIGOS') LIMIT 1), true),
('633001', 'Instalar Armação Secundária', 'Unidade', 0.2, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633002', 'Retirar  Armação Secundária', 'Unidade', 0.08, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633004', 'Instalar Armação Secundária HE', 'Unidade', 0.277, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633005', 'Retirar Armação Secundária HE', 'Unidade', 0.111, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633011', 'Instalar Afastador Secundário', 'Unidade', 0.3, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633012', 'Retirar  Afastador Secundário', 'Unidade', 0.12, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633014', 'Instalar Afastador Secundário HE', 'Unidade', 0.416, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633015', 'Retirar  Afastador Secundário HE', 'Unidade', 0.166, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633071', 'Inst. Conj. Grampo Susp.Cabo Multiplex.', 'Unidade', 0.301, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633072', 'Ret. Conj. Grampo Susp.Cabo Multiplex.', 'Unidade', 0.12, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633074', 'InstConj Grampo Susp.Cabo Multiplex HE', 'Unidade', 0.417, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('633075', 'RetConj Grampo Susp.Cabo Multiplex. HE', 'Unidade', 0.166, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635161', 'Balanceamento Rede Secundária', 'Unidade', 0.024, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635164', 'Balanceamento Rede Secundária HE', 'Unidade', 0.033, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635173', 'Tensionamento do Ramal de Ligação', 'Unidade', 0.016, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635176', 'Tensionamento do Ramal de Ligação HE', 'Unidade', 0.022, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635181', 'Instalar Espaçador de Baixa Tensão', 'Unidade', 0.12, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635182', 'Retirar  Espaçador de Baixa Tensão', 'Unidade', 0.12, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635184', 'Instalar Espaçador de Baixa Tensão HE', 'Unidade', 0.166, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635185', 'Retirar  Espaçador de Baixa Tensão HE', 'Unidade', 0.166, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635191', 'InstCond Multiplex.BT Seção Fase=35 mm²', 'km', 30, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635192', 'Ret Cond Multiplex BT Seção Fase=35 mm²', 'km', 12, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635194', 'Inst Cond Multiplex.BT Seção =35 mm² HE', 'km', 42, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635195', 'Ret Cond Multiplex BT Seção =35 mm² HE', 'km', 16, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635201', 'Inst Cond Multiplex BT Seção Fase=50 mm²', 'km', 33, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635202', 'Ret Cond Multiplex BT Seção Fase=50mm²', 'km', 13.2, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635204', 'Inst Cond Multiplex BT Seção =50 mm² HE', 'km', 46, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635205', 'Ret Cond Multiplex BT Seção =50mm² HE', 'km', 18, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635211', 'Inst Cond Multiplex BT Seção Fase=70mm²', 'km', 36, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635212', 'Ret Cond Multiplex BT Seção Fase=70mm²', 'km', 14, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635214', 'Inst Cond Multiplex BT Seção =70mm² HE', 'km', 50, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635215', 'Ret Cond Multiplex BT Seção =70mm² HE', 'km', 20, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635221', 'Inst Cond Multiplex BT Seção Fase=120mm²', 'km', 40, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635222', 'Ret Cond Multiplex BT Seção Fase=120mm²', 'km', 15, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635224', 'Inst Cond Multiplex BT Seção =120mm² HE', 'km', 55, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635225', 'Ret Cond Multiplex BT Seção =120mm² HE', 'km', 20, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635231', 'Instalar Conector de BT, Tipo Perfurante ou ampactinho', 'Unidade', 0.06, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635232', 'Retirar  Conector de BT, Tipo Perfurante ou ampactinho', 'Unidade', 0.024, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635234', 'Inst. Conector de BT, Tipo Perfurante ou ampactinho HE', 'Unidade', 0.083, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635235', 'Ret.  Conector de BT Tipo Perfurante ou ampactinho HE', 'Unidade', 0.033, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635251', 'Emenda Cabo Multip.BT Seção 35 a 120mm²', 'Unidade', 0.18, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635254', 'Emenda Cabo Multip.BT Seção 35a120mm² HE', 'Unidade', 0.25, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635261', 'Inst Flying-Tap/Cruzam.Aéreo,RDMultipl.', 'Unidade', 0.06, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true),
('635262', 'Ret Flying-Tap/CruzamAéreo, RD Multipl.', 'Unidade', 0.024, (SELECT id FROM categorias WHERE LOWER(nome) = LOWER('ESTRUTURA DE BAIXA TENSÃO') LIMIT 1), true)
ON CONFLICT (codigo_item) DO UPDATE SET 
  descricao = EXCLUDED.descricao,
  unidade = EXCLUDED.unidade,
  umd_unitaria = EXCLUDED.umd_unitaria,
  categoria_id = EXCLUDED.categoria_id,
  ativo = true;